# Generated by Django 4.2.5 on 2023-10-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_post_options_remove_post_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autthor',
            new_name='author',
        ),
    ]
